repos:
-   repo: https://github.com/sirosen/check-jsonschema
    rev: 0.6.0
    hooks:
      - id: check-jsonschema
        name: "Validate Json"
        files: geojson
        types: [file]
        args: ["--schemafile","./community.schema.json"]